(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='pse.plan.v2', SESSION='pse.session.v2', PREF='pse.pref.v2';
const hashByScreen={homeScreen:'#inicio',useScreen:'#agora',editScreen:'#revisar'};
const screenByHash={'#inicio':'homeScreen','#agora':'useScreen','#revisar':'editScreen'};
let step=0, voiceActive=false, currentVoiceButton=null, printHeights=[];
const fields=['signals','internal','social','trustedPerson','trustedContact','trustedMessage','professional','professionalContact','urgentService','saferEnvironment','reasons'];
const stepDefs=[
  {label:'1 · Sinais de alerta',title:'Reconheça o que está acontecendo',prompt:'Nomear sinais pode ajudar a perceber que este é um momento de crise — não uma ordem para agir.',key:'signals',fallback:'Observe se aparecem mudanças conhecidas no corpo, pensamentos, emoções ou comportamento. Se reconhecer seus sinais habituais, passe ao próximo passo.'},
  {label:'2 · Estratégias internas',title:'Ganhe alguns minutos antes de decidir',prompt:'Use uma estratégia simples e segura que já tenha sido combinada ou treinada fora do pico.',key:'internal',fallback:'Reduza a tarefa ao próximo minuto: mude de posição, perceba o apoio do corpo, olhe ao redor e respire de forma confortável.',extra:'tools'},
  {label:'3 · Pessoas e lugares',title:'Aproxime-se de um contexto mais seguro',prompt:'Você não precisa explicar tudo. O objetivo é diminuir isolamento e ganhar tempo em um ambiente previsível.',key:'social',fallback:'Vá para perto de uma pessoa confiável ou para um local conhecido e com outras pessoas por perto.'},
  {label:'4 · Pedir ajuda',title:'Diga claramente que precisa de companhia',prompt:'Quando a crise aumenta, ser direto costuma exigir menos energia do que explicar toda a situação.',key:'trusted',fallback:'Escolha uma pessoa adulta de confiança e diga algo simples como: “Não estou bem e preciso que você fique comigo agora.”'},
  {label:'5 · Profissionais e serviços',title:'Suba o nível de apoio quando precisar',prompt:'Use os contatos definidos previamente. Se você não consegue permanecer seguro, procure atendimento presencial de urgência ou emergência.',key:'professional',fallback:'Procure seu profissional ou serviço de referência. Se não consegue permanecer seguro, vá para atendimento presencial de urgência ou emergência.',extra:'help'},
  {label:'6 · Ambiente mais seguro',title:'Reduza exposição ao que aumenta risco',prompt:'Peça ajuda para organizar o ambiente e permanecer perto de alguém. Não precisa fazer isso sozinho.',key:'saferEnvironment',fallback:'Fique perto de uma pessoa de confiança, mude para um ambiente mais seguro e peça ajuda para reduzir exposição a situações ou objetos que aumentem risco.'},
  {label:'7 · Ganhar tempo',title:'Lembre do que importa agora',prompt:'Você não precisa sentir esperança para ganhar tempo. Basta reconhecer algo que vale proteger por mais alguns minutos.',key:'reasons',fallback:'Pense apenas no próximo intervalo de tempo. Escolha um motivo genuíno — pessoa, valor, cuidado, compromisso, projeto, fé ou curiosidade — para adiar decisões e permanecer acompanhado.'}
];
function storageGet(storage,k){try{return storage.getItem(k)}catch{return null}}
function storageSet(storage,k,v){try{storage.setItem(k,v);return true}catch{return false}}
function storageRemove(storage,k){try{storage.removeItem(k);return true}catch{return false}}
function safeJson(storage,k,d){try{return JSON.parse(storageGet(storage,k)||'null')??d}catch{return d}}
function plan(){return safeJson(localStorage,KEY,null)}
function reducedMotion(){return matchMedia('(prefers-reduced-motion:reduce)').matches}
function setHistory(id,mode){const hash=hashByScreen[id]||'#inicio',state={screen:id,fromApp:mode==='push'};if(mode==='replace')history.replaceState(state,'',hash);else if(mode==='push')history.pushState(state,'',hash)}
function show(id,historyMode='push'){stopVoice();$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));if(historyMode)setHistory(id,historyMode);window.scrollTo({top:0,behavior:reducedMotion()?'auto':'smooth'});if(id==='useScreen'){step=0;renderUse()}if(id==='editScreen')loadForm()}
function goHome(){if(history.state?.fromApp)history.back();else show('homeScreen','replace')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2300)}
function collect(){return Object.fromEntries(fields.map(id=>[id,$('#'+id).value.trim()]))}
function loadForm(){const saved=plan(), temp=storageGet(sessionStorage,SESSION);let data=saved||{};if(temp){try{data={...data,...JSON.parse(temp)}}catch{}}fields.forEach(id=>{$('#'+id).value=data[id]||''});const at=storageGet(localStorage,KEY+'.at');$('#savedAt').textContent=at?`Última gravação neste dispositivo: ${new Date(at).toLocaleString('pt-BR')}`:'Nada foi salvo permanentemente neste dispositivo.'}
function autosaveSession(){storageSet(sessionStorage,SESSION,JSON.stringify(collect()))}
function savePlan(){const data=collect(),serialized=JSON.stringify(data);if(!storageSet(localStorage,KEY,serialized)){storageSet(sessionStorage,SESSION,serialized);toast('Não foi possível salvar permanentemente neste navegador.');return}storageSet(localStorage,KEY+'.at',new Date().toISOString());storageSet(sessionStorage,SESSION,serialized);loadForm();toast('Plano salvo somente neste dispositivo.')}
function clearPlan(){if(!confirm('Apagar o plano salvo neste dispositivo?'))return;storageRemove(localStorage,KEY);storageRemove(localStorage,KEY+'.at');storageRemove(sessionStorage,SESSION);$('#planForm').reset();loadForm();toast('Dados locais apagados.')}
function stepContent(def,p){if(!p)return'';if(def.key==='trusted')return [p.trustedPerson,p.trustedContact,p.trustedMessage].filter(Boolean).join('\n');if(def.key==='professional')return [p.professional,p.professionalContact,p.urgentService].filter(Boolean).join('\n');return p[def.key]||''}
function renderUse(){const p=plan(),status=$('#planStatus');if(p){status.className='shell plan-status ok';const at=storageGet(localStorage,KEY+'.at');status.innerHTML=`<strong>Plano personalizado carregado.</strong><p>${at?`Última revisão local: ${new Date(at).toLocaleDateString('pt-BR')}. `:''}Use apenas o próximo passo.</p>`}else{status.className='shell plan-status warn';status.innerHTML='<strong>Este dispositivo não tem um plano salvo.</strong><p>As orientações abaixo são gerais. Quando houver estabilidade, monte o plano com seu profissional e uma pessoa de confiança.</p>'}renderStep()}
function renderStep(){stopVoice();const def=stepDefs[step],p=plan(),content=stepContent(def,p);$('#stepCounter').textContent=`Passo ${step+1} de ${stepDefs.length}`;$('#stepLabel').textContent=def.label;$('#stepTitle').textContent=def.title;$('#stepPrompt').textContent=def.prompt;const box=$('#stepSaved');box.className='saved-content'+(content?'':' empty');box.textContent=content||def.fallback;$('#prevStepBtn').disabled=step===0;$('#nextStepBtn').textContent=step===stepDefs.length-1?'Recomeçar os passos':'Próximo passo';const extra=$('#stepExtra');extra.innerHTML='';if(def.extra==='tools'){const wrap=document.createElement('div');wrap.className='mini-actions';wrap.innerHTML='<button class="btn subtle" type="button" data-audio="ground" aria-pressed="false">Ouvir orientação ao presente</button><button class="btn subtle" type="button" data-audio="breath" aria-pressed="false">Ouvir respiração confortável</button>';extra.appendChild(wrap);wrap.querySelector('[data-audio="ground"]').onclick=groundAudio;wrap.querySelector('[data-audio="breath"]').onclick=breathAudio}if(def.extra==='help'){const b=document.createElement('button');b.className='btn subtle';b.type='button';b.textContent='Abrir opções de ajuda humana';b.onclick=openHelp;extra.appendChild(b)}}
function next(){if(step===stepDefs.length-1)step=0;else step++;renderStep();window.scrollTo({top:$('#crisisStep').offsetTop-72,behavior:reducedMotion()?'auto':'smooth'})}
function prev(){if(step>0){step--;renderStep()}}
function setVoiceButton(button,active,label='Parar áudio'){if(!button)return;if(active){if(!button.dataset.idleLabel)button.dataset.idleLabel=button.textContent;button.textContent=label;button.setAttribute('aria-pressed','true')}else{button.textContent=button.dataset.idleLabel||button.textContent;button.setAttribute('aria-pressed','false')}}
function finishVoice(button){if(currentVoiceButton!==button)return;voiceActive=false;setVoiceButton(button,false);currentVoiceButton=null}
function stopVoice(){if('speechSynthesis'in window)speechSynthesis.cancel();if(currentVoiceButton)setVoiceButton(currentVoiceButton,false);voiceActive=false;currentVoiceButton=null;const b=$('#speakStepBtn');if(b)b.setAttribute('aria-pressed','false')}
function speak(text,button,stopLabel='Parar voz'){if(voiceActive&&currentVoiceButton===button){stopVoice();return}stopVoice();if(!('speechSynthesis'in window)){toast('A voz não está disponível neste navegador.');return}const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=.86;u.pitch=1;voiceActive=true;currentVoiceButton=button;setVoiceButton(button,true,stopLabel);u.onend=()=>finishVoice(button);u.onerror=()=>finishVoice(button);speechSynthesis.speak(u)}
function speakStep(){const def=stepDefs[step],txt=$('#stepSaved').textContent;speak(`${def.title}. ${def.prompt}. ${txt}`,$('#speakStepBtn'),'Parar voz')}
function sequence(parts,button){if(voiceActive&&currentVoiceButton===button){stopVoice();return}stopVoice();if(!('speechSynthesis'in window)){toast('A voz não está disponível neste navegador.');return}voiceActive=true;currentVoiceButton=button;setVoiceButton(button,true,'Parar orientação');let i=0;const run=()=>{if(!voiceActive||currentVoiceButton!==button)return;if(i>=parts.length){finishVoice(button);return}const u=new SpeechSynthesisUtterance(parts[i++]);u.lang='pt-BR';u.rate=.82;u.onend=run;u.onerror=()=>finishVoice(button);speechSynthesis.speak(u)};run()}
function groundAudio(e){sequence(['Olhe ao redor sem pressa.','Encontre três coisas neutras que você consegue ver.','Perceba agora dois pontos de apoio do seu corpo, como os pés no chão ou as costas na cadeira.','Escute um som próximo ou distante.','Você não precisa resolver tudo neste momento. Apenas escolha o próximo passo seguro.'],e?.currentTarget||null)}
function breathAudio(e){sequence(['Deixe a respiração acontecer sem forçar.','Inspire de forma confortável.','Solte o ar devagar, sem prender a respiração.','Se for confortável, deixe a saída do ar um pouco mais longa.','Volte à respiração espontânea. Se houver tontura, falta de ar ou piora do desconforto, pare.'],e?.currentTarget||null)}
function addHelpItem(list,label,value){if(!value)return;const item=document.createElement('div');item.className='personal-help-item';const strong=document.createElement('strong');strong.textContent=value;const span=document.createElement('span');span.textContent=label;item.append(strong,span);list.appendChild(item)}
function renderHelp(){const p=plan(),box=$('#personalHelp'),list=$('#personalHelpList');list.className='personal-help-list';list.replaceChildren();if(p){addHelpItem(list,'Pessoa de confiança',p.trustedPerson);addHelpItem(list,'Contato da pessoa de confiança',p.trustedContact);addHelpItem(list,'Profissional ou serviço',p.professional);addHelpItem(list,'Contato profissional',p.professionalContact);addHelpItem(list,'Atendimento presencial definido',p.urgentService)}box.hidden=!list.childElementCount}
function openHelp(){stopVoice();renderHelp();$('#helpDialog').showModal()}
function prefs(){return safeJson(localStorage,PREF,{})}
function applyPrefs(){const p=prefs(),theme=p.theme||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'),scale=Math.min(1.2,Math.max(1,Number(p.scale||1)));document.documentElement.dataset.theme=theme;document.documentElement.style.setProperty('--scale',scale)}
function setPref(obj){if(!storageSet(localStorage,PREF,JSON.stringify({...prefs(),...obj})))toast('Preferência aplicada apenas nesta sessão.')}
function preparePrint(){printHeights=$$('textarea').map(a=>a.style.height);$$('textarea').forEach(a=>{a.style.height='auto';a.style.height=`${a.scrollHeight}px`})}
function restorePrint(){$$('textarea').forEach((a,i)=>a.style.height=printHeights[i]||'');printHeights=[]}
function wire(){
  $('#usePlanBtn').onclick=()=>show('useScreen','push');$('#editPlanBtn').onclick=()=>show('editScreen','push');$$('[data-go="home"]').forEach(b=>b.onclick=goHome);
  $('#urgentHelpBtn').onclick=openHelp;$('#urgentHelpBtn2').onclick=openHelp;$('#prevStepBtn').onclick=prev;$('#nextStepBtn').onclick=next;$('#speakStepBtn').onclick=speakStep;$('#groundingAudioBtn').onclick=groundAudio;$('#groundingAudioBtn2').onclick=groundAudio;$('#breathingAudioBtn').onclick=breathAudio;
  $('#planForm').addEventListener('input',autosaveSession);$('#savePlanBtn').onclick=savePlan;$('#clearPlanBtn').onclick=clearPlan;$('#printPlanBtn').onclick=()=>{preparePrint();window.print()};
  $('#themeBtn').onclick=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;setPref({theme:n})};
  $('#textSizeBtn').onclick=()=>{const cur=Number(prefs().scale||1),n=cur>=1.2?1:Number((cur+.1).toFixed(1));document.documentElement.style.setProperty('--scale',n);setPref({scale:n});toast(n===1?'Texto no tamanho padrão.':`Texto ampliado para ${Math.round(n*100)}%.`)};
  $('#helpDialog').addEventListener('close',stopVoice);window.addEventListener('afterprint',restorePrint);window.addEventListener('popstate',e=>show(e.state?.screen||screenByHash[location.hash]||'homeScreen',null));
}
applyPrefs();wire();show(screenByHash[location.hash]||'homeScreen','replace');if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();